/**
 * Card API
 * Find customer cards
 *
 * OpenAPI spec version: 1.0.0
 * Contact: clement.hosotte@capemini.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * card details
 */
export interface Card {
    id?: number;
    owner?: string;
    expirationDate?: string;
    ceiling?: number;
}
